spring:
  application:
    name: authservice

server:
  port: 8081

kakao:
  client-id: ${KAKAO_CLIENT_ID:YOUR_KAKAO_REST_API_KEY}
  client-secret: ${KAKAO_CLIENT_SECRET:}
  redirect-uri: http://localhost:8080/api/auth/kakao/callback
  front-callback-url: http://localhost:3000/auth/kakao
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

google:
  client-id: YOUR_GOOGLE_CLIENT_ID
  client-secret: YOUR_GOOGLE_CLIENT_SECRET
  redirect-uri: http://localhost:8080/api/auth/google/callback
  front-callback-url: http://localhost:3000/auth/google

naver:
  client-id: ${NAVER_CLIENT_ID:YOUR_NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET:YOUR_NAVER_CLIENT_SECRET}
  redirect-uri: http://localhost:8080/api/auth/naver/callback
  front-callback-url: http://localhost:3000/auth/naver
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
